# Generated by Django 3.1.7 on 2021-07-27 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApproachAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'ApproachAct',
                'verbose_name_plural': 'ApproachesAct',
            },
        ),
        migrations.CreateModel(
            name='ColorAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ColorAct',
                'verbose_name_plural': 'ColorsAct',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_Name', models.CharField(max_length=400)),
                ('Department_ID', models.CharField(max_length=200)),
                ('Module_Name', models.CharField(max_length=400)),
                ('Module_ID', models.CharField(max_length=200)),
                ('Faculty', models.CharField(max_length=400)),
                ('Credit_Value', models.IntegerField(blank=True, default=0, null=True)),
                ('Module_Lead', models.CharField(blank=True, max_length=200, null=True)),
                ('Catalogue_Link', models.CharField(max_length=400)),
                ('Description', models.TextField(blank=True, null=True)),
                ('assignedSDG', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('data', models.JSONField(blank=True, null=True)),
                ('assignedSDG', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PyChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('picture', models.ImageField(blank=True, default='', null=True, upload_to='charts/')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialtyAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coloract')),
            ],
            options={
                'verbose_name': 'SpecialtyAct',
                'verbose_name_plural': 'SpecialtiesAct',
            },
        ),
        migrations.CreateModel(
            name='UserProfileAct',
            fields=[
                ('author_id', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('fullName', models.CharField(default='', max_length=100)),
                ('scopusLink', models.URLField(default='', null=True)),
                ('affiliation', models.TextField(blank=True, null=True)),
                ('affiliationID', models.CharField(default='', max_length=200)),
                ('approach', models.ManyToManyField(blank=True, to='app.ApproachAct')),
                ('specialty', models.ManyToManyField(blank=True, to='app.SpecialtyAct')),
            ],
            options={
                'verbose_name': 'UserProfileAct',
                'verbose_name_plural': 'UserProfilesAct',
            },
        ),
        migrations.CreateModel(
            name='BubbleAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_people', models.TextField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coloract')),
                ('coordinate_approach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.approachact')),
                ('coordinate_speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.specialtyact')),
            ],
        ),
    ]
