# Generated by Django 3.2.5 on 2021-08-09 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='String_SpecialtyAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coloract')),
            ],
            options={
                'verbose_name': 'StringSpecialtyAct',
                'verbose_name_plural': 'StringSpecialtiesAct',
            },
        ),
    ]
