# Generated by Django 3.2.5 on 2021-08-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210809_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialtyact',
            name='methodology',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='String_SpecialtyAct',
        ),
    ]
