# Generated by Django 3.1.7 on 2021-06-23 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210623_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bubble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate_approach', models.IntegerField(blank=True, default=0, null=True)),
                ('coordinate_speciality', models.IntegerField(blank=True, default=0, null=True)),
                ('list_of_people', models.TextField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.color')),
            ],
        ),
        migrations.DeleteModel(
            name='Serializer',
        ),
    ]
