# Generated by Django 3.1.7 on 2021-06-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210623_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='index',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
