# Generated by Django 3.1.7 on 2021-06-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210623_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={},
        ),
    ]
