# Generated by Django 3.1.7 on 2021-06-30 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210630_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproachAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'ApproachAct',
                'verbose_name_plural': 'ApproachesAct',
            },
        ),
        migrations.CreateModel(
            name='ColorAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ColorAct',
                'verbose_name_plural': 'ColorsAct',
            },
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='SpecialtyAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coloract')),
            ],
            options={
                'verbose_name': 'SpecialtyAct',
                'verbose_name_plural': 'SpecialtiesAct',
            },
        ),
        migrations.CreateModel(
            name='BubbleAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_people', models.TextField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.color')),
                ('coordinate_approach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.approachact')),
                ('coordinate_speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.specialtyact')),
            ],
        ),
    ]
