# Generated by Django 3.1.7 on 2021-06-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210630_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileAct',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('fullName', models.CharField(default='', max_length=100)),
                ('scopusLink', models.URLField(default='', null=True)),
                ('faculty', models.CharField(default='', max_length=200)),
                ('approach', models.ManyToManyField(blank=True, to='app.ApproachAct')),
                ('specialty', models.ManyToManyField(blank=True, to='app.SpecialtyAct')),
            ],
            options={
                'verbose_name': 'UserProfileAct',
                'verbose_name_plural': 'UserProfilesAct',
            },
        ),
    ]
