# Generated by Django 3.1.7 on 2021-06-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210630_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileact',
            name='affiliation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileact',
            name='author_id',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
