# Generated by Django 3.1.7 on 2021-07-01 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210630_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bubbleact',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coloract'),
        ),
    ]
